name: Check Base Branch

on:
  pull_request:
    types: [opened]
    branches:
      - stable

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Base Branch
        run: | 
          echo "::error ::Base branch of PR is stable. It should be main. Please retarget the base branch of the PR." 
          exit 1

