name: Publish Stable to Year
on:
  push:
    branches:
      - stable
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'wpilibsuite' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.ff only

          git fetch origin stable
          (git checkout stable && git pull) || git checkout -b stable origin/stable

          git fetch origin ${{ secrets.STABLE_YEAR }}
          (git checkout ${{ secrets.STABLE_YEAR }} && git pull) || git checkout -b ${{ secrets.STABLE_YEAR }} origin/${{ secrets.STABLE_YEAR }}

          if git merge-base --is-ancestor stable ${{ secrets.STABLE_YEAR }}; then
            echo "No merge is necessary"
            exit 0
          fi;

          git merge --ff-only stable

      - name: Push
        if: env.PUBLISH_STABLE == 'true' || github.event.action == 'workflow_dispatch'
        env:
          PUBLISH_STABLE: ${{ secrets.PUBLISH_STABLE }}
        run: |
          git push origin ${{ secrets.STABLE_YEAR }}
