name: Update Translations
on:
  push:
    paths:
    - '.github/workflows/update-translations.yml'
  schedule:
    - cron:  '0 6 * * *'
jobs:
  update-translations:
    runs-on: ubuntu-latest
    if: github.repository == 'wpilibsuite/frc-docs'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source/requirements.txt
      - name: Pull Translations
        run: tx pull -l fr_CA,es_MX --mode onlyreviewed --use-git-timestamps
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.8.0
        with:
          commit-message: Update translations
          title: Update translations
          body: |
              Updates the translations to the latest reviewed in Transifex.

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
          labels: i18n
          branch: automation/update-translations
